version: "3.7"

services:
  todo-list:
    image: diamol/ch09-todo-list
    ports:
      - "8083:80"
    networks:
      - app-net
  prometheus:
    #image: diamol/ch09-lab-prometheus
    build: ./prometheus
    ports:
      - "9090:9090"
    networks:
      - app-net
  grafana:
    # build grafana image
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net
networks:
  app-net:
    external:
      name: nat
