version: "3.8"
services:
  jenkins:
    build:
      context: .
    image: haquan/jenkins-docker
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    healthcheck:
      test: curl -s https://localhost:8081 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 1m
      timeout: 5s
      retries: 3
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
