version: "3.7"

services:
  todo-db:
    image: diamol/postgres:11.5
    ports:
      - "${TODO_DB_PORT}:5432"
    environment:
      - PGDATA=/data
    volumes:
      - "todo-database:/data"
    networks:
      - app-net

  todo-web:
    image: diamol/ch06-todo-list:latest
    environment:
      - Database:Provider=Postgres
    ports:
      - "${TODO_WEB_PORT}:80"
    depends_on:
      - todo-db
    networks:
      - app-net

networks:
  app-net:
    name: todo-test

secrets:
  todo-db-connection:
    file: ./config/secrets.json
volumes:
  todo-database:
